### ISSUE TITLE
Can not run any code

### ISSUE THREAD

**Issue by sproblvem** [deepmind/ai-safety-gridworlds#10]
Hi, I am trying to run the code on my computer. I have encountered with several problems. I followed the instruction in README.But, I tried environment python files in the environment directory, they all report the following error message.

> File "build/bdist.linux-x86_64/egg/pycolab/human_ui.py", line 333, in _display
> AttributeError: 'numpy.ndarray' object has no attribute 'board'

My python version is 
> Python 2.7.15rc1

Numpy version is
> numpy==1.15.0

I believe the README is out of date, can you update it, or we dont know how to run this code.

**Comment by taineleau-zz** [comment]
Hi, I ran it yesterday and everything is fine. maybe you can create a clean virtual environment to rerun it again?

**Comment by sproblvem** [comment]
I found the root cause of this issue. This repo relies on a specific version of pycolab

> Submodule path 'pycolab': checked out 'b389d1e7ef949863561047d358a1661c298d382f'

The latest version of pycolab will cause this problem...
