### ISSUE TITLE
ModuleNotFoundError: No module named 'ai_safety_gridworlds'

### ISSUE THREAD

**Issue by 2phx** [deepmind/ai-safety-gridworlds#16]
Running Ubuntu 18.04 from Windows 10 WSL.
Installed everything as per instructions. Pycolab examples work fine.

Running any environment.py as per instructions I am getting: 
ModuleNotFoundError: No module named 'ai_safety_gridworlds'

What I am doing wrong? Help appreciated. 

Full error:
--
Traceback (most recent call last):
  File "friend_foe.py", line 58, in <module>
    from ai_safety_gridworlds.environments.shared import safety_game
ModuleNotFoundError: No module named 'ai_safety_gridworlds'

**Comment by miljanm** [comment]
Hi, 

The library hasn't been tested on the WSL Ubuntu platform, but can you try the following:

I'm assuming you have git cloned in `$HOME` so there is `$HOME/ai-safety-gridworlds`.

```bash
cd ~
export PYTHONPATH=${PYTHONPATH}:${HOME}/ai-safety-gridworlds
cd ai-safety-gridworlds
python ai_safety_gridworlds/environments/friend_foe.py
```

Are you using the virtual environment? In what folder did you instantiate it?
If the above doesn't work, can you also run:

```bash
which python
python -V
ls $HOME/ai-safety-gridworlds
```

and let me know the outputs?

**Comment by 2phx** [comment]
Thank you for your reply. 

Yea I have git cloned it to $HOME .
I did the following as you recommended:
```
cd ~
export PYTHONPATH=${PYTHONPATH}:${HOME}/ai-safety-gridworlds
cd ai-safety-gridworlds
python ai_safety_gridworlds/environments/friend_foe.py
```

Now everything is working perfectly fine. 

`python3 ai_safety_gridworlds/environments/friend_foe.py  `

https://i.imgur.com/OFFpStu.png


Thanks a lot!
