### ISSUE TITLE
Add Python 3 compatibility

### ISSUE THREAD

**Issue by stevenschmatz** [deepmind/ai-safety-gridworlds#2]
I'm curious to find why Python 2.7.13 was chosen. To me, it would seem to make more sense if Python 3 compatibility was at least added with `__future__` statements.

**Comment by janleike** [comment]
Thanks for your question! Python 2.7 was chosen because it is the version of choice at DeepMind/Google. We are using some future imports, but haven't tested Python 3 compatibility. If you want to make a pull request, we'd be delighted to review it. :)

**Comment by stevenschmatz** [comment]
I'll work on this and send a pull request in a day or two!

**Comment by janleike** [comment]
Awesome! :)

**Comment by pierg** [comment]
Hello,
Any news about the python 3 compatibility? I have an A2C implementation of the agent in python 3 and I am experiencing compatibility problems when I connect it to the gridworld-safety environment and pycolab libraries.
Thanks!! :)

**Comment by miljanm** [comment]
Latest version of the library now adds support for both py2 and py3.
