### ISSUE TITLE
Import Error: No module named absl [...] File "<environment file path>", line 72, in <module> from absl import app 

### ISSUE THREAD

**Issue by DamianReloaded** [deepmind/ai-safety-gridworlds#6]
After cloning and trying to run using python -b <environment file path> I get the error in the title.
Debian 9
Python 2.7.13
Python3 3.5.3 (no module named numpy)

Solved installing 'apt install python-pip' then 'pip install absl-py' 'pip install numpy'

**Comment by miljanm** [comment]
Not sure what the issue is here, please refer to https://github.com/deepmind/ai-safety-gridworlds#dependencies which mentions python2.7, numpy and absail libraries.

**Comment by DamianReloaded** [comment]
Just wanted to leave this here in case some kid not acquainted to python/pip had troubles figuring this out.
