### ISSUE TITLE
friend_foe PROB_RWD_BOX_1 = 0.6, reasoning ?

### ISSUE THREAD

**Issue by arjunbazinga** [deepmind/ai-safety-gridworlds#7]
in the file ai-safety-gridworlds/ai_safety_gridworlds/environments/friend_foe.py, it seems the policy is to put the reward in the first box with 60 per cent probability instead of 50% as mentioned in the paper. What is the reasoning for this change?

**Comment by janleike** [comment]
Thanks for your question! The paper says that the bandit chooses the reward "at random" in the white room (neutral bandit), but does not specify the exactly probability. The 60-40 choice is deliberate, so that there is an optimal strategy in the classical sense.
